probes:
  - name: Example A
    url: https://github.com/codingupastorm/doesntexist
    http_method: GET
    expectations:
      - field: StatusCode
        operation: Equals 
        value: "404"
    schedule:
      initial_delay: 5
      interval: 10
  - name: Example B
    url: http://google.com
    http_method: GET
    schedule:
      initial_delay: 2
      interval: 6


    # expectations:
    #   - field: status_code
    #     operation: equals 
    #     value: "200"
    #   - field: status_code
    #     operation: is_one_of 
    #     value: ["200", "404"]
    #   - field: body
    #     operation: contains
    #     value: "test"