probes:
  - name: app-suitsbooks-com
    url:	https://app.suitsbooks.com
    http_method: GET
    expectations:
      - field: StatusCode
        operation: Equals 
        value: "200"
    schedule:
      initial_delay: 0
      interval: 30
    alerts:
      - url: https://discord.com/api/webhooks/1431818669641699350/GL6apti2l6RZGWZhi6gsw4hR35c3yRUUKjxqPN69ZF-G0nMP768WpX8oMR4DQnMzzilU

