probes:
  - name: Example A
    url: http://codingupastorm.dev
    expect_back:
      status_code: "200"
    schedule:
      initial_delay: 5
      interval: 10
  - name: Example B
    url: http://google.com
    expect_back:
      status_code: "200"
    schedule:
      initial_delay: 2
      interval: 6