probes:
  - name: Example A
    url: https://github.com/codingupastorm/doesntexist
    http_method: GET
    expect_back:
      status_code: "200"
    schedule:
      initial_delay: 5
      interval: 10
  - name: Example B
    url: http://google.com
    http_method: GET
    expect_back:
      status_code: "200"
    schedule:
      initial_delay: 2
      interval: 6